# Generated by Django 4.2 on 2024-12-19 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Espacio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_administrados', to=settings.AUTH_USER_MODEL)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='espacios_colaborados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
